//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecipitacaoMdl
    {
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string Bacia { get; set; }
        public string SubBacia { get; set; }
        public double Precipitacao1 { get; set; }
        public string Fonte { get; set; }
    }
}
